version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: financial_tracker
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    command: sh -c "sleep 10 && ./main"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: password
      DB_NAME: financial_tracker
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .env:/app/.env
