version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: financial_tracker
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: financial_tracker
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
